@startuml

title "BEST: stand-alone DB + API (dockerized)"
center header "Bart Hanssens - 2022-01-12"

cloud "Open Data BOSA" {
	folder "Downloads" as folderDownload {
		file "BeST Full Download (ZIP)" as fileFull
	}
}

rectangle "Local system" {
	component "Unzip tool" as cUnzip {
	}

	folder XML as folderXML {
		collections "Brussels XML"
		collections "Flanders XML"
		collections "Wallonia XML"
	}

	component "Convert tool" as cConvert {
		component XMLReader
	}

	folder CSV as folderCSV {
		file "Address"
		file "Municipality"
		file "MunicipalityPart"
		file "Street"
		file "PostalInfo"
	}

	package "Docker image" as dockerImage {
		database PostGIS as dbPg
			component "REST API" as cAPI
	}
}

cloud "Docker repository" as hubDocker {
}

cloud "Data center" {
		package "Docker container" as dContainer {
	}
}

actor User as user

fileFull -right-> cUnzip
cUnzip -down-> folderXML
folderXML -up-> cConvert
cConvert -down-> folderCSV
folderCSV -up-> dbPg
dbPg -right- cAPI
dockerImage -right-> hubDocker
dContainer -down-> hubDocker
user -> dContainer

@enduml