version: "3.5"
services:
  web:
    image: "barthanssens/best-webservice"
    links:
      - "db:db"
    ports:
      - "8080:8080"
    networks:
      bestnet: {}
    environment:
      - quarkus.datasource.reactive.url=postgresql://db:5432/best
  db:
    image: "barthanssens/best-webservice-postgis"
    ports:
      - "5432:5432"
    networks:
      bestnet: {}

networks:
  bestnet:
    name: best

